//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BH_DE_NGHI_GIU_HANG
    {
        public int MA_SO_DN { get; set; }
        public System.DateTime NGAY_DN { get; set; }
        public System.DateTime NGAY_XUAT { get; set; }
        public string SALES_DN { get; set; }
        public string KHACH_HANG { get; set; }
        public string MA_HANG { get; set; }
        public int SL_GIU { get; set; }
        public string LOAI_GIU { get; set; }
        public bool DA_GIU { get; set; }
        public bool CHUA_GIU { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual KH KH { get; set; }
        public virtual HH HH { get; set; }
        public virtual CCTC_NHAN_VIEN CCTC_NHAN_VIEN { get; set; }
    }
}
