//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORy()
        {
            this.CATEGORIES1 = new HashSet<CATEGORy>();
            this.POST_CATEGORIES = new HashSet<POST_CATEGORIES>();
        }
    
        public string MA_DANH_MUC { get; set; }
        public string TEN_DANH_MUC { get; set; }
        public string MA_DANH_MUC_CHA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATEGORy> CATEGORIES1 { get; set; }
        public virtual CATEGORy CATEGORy1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POST_CATEGORIES> POST_CATEGORIES { get; set; }
    }
}
