//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTC_BANG_LUONG
    {
        public string THANG_LUONG { get; set; }
        public string USERNAME { get; set; }
        public decimal LUONG_CO_BAN { get; set; }
        public decimal LUONG_BAO_HIEM { get; set; }
        public decimal PHU_CAP_AN_TRUA { get; set; }
        public decimal PHU_CAP_DI_LAI_DIEN_THOAI { get; set; }
        public decimal PHU_CAP_THUONG_DOANH_SO { get; set; }
        public decimal PHU_CAP_TRACH_NHIEM { get; set; }
        public double CONG_CO_BAN { get; set; }
        public decimal LUONG_CO_BAN_NGAY { get; set; }
        public decimal LUONG_CO_BAN_GIO { get; set; }
        public decimal BAO_HIEM_CONG_TY_DONG { get; set; }
        public decimal BAO_HIEM_NHAN_VIEN_DONG { get; set; }
        public double LUONG_THUC_TE_CONG_LAM_THUC { get; set; }
        public decimal LUONG_THUC_TE_SO_TIEN { get; set; }
        public double LUONG_LAM_THEM_CONG_NGAY_THUONG { get; set; }
        public decimal LUONG_LAM_THEM_TIEN_CONG_NGAY_THUONG { get; set; }
        public double LUONG_LAM_THEM_CONG_NGAY_NGHI { get; set; }
        public decimal LUONG_LAM_THEM_TIEN_CONG_NGAY_NGHI { get; set; }
        public double LUONG_LAM_THEM_CONG_NGAY_LE { get; set; }
        public decimal LUONG_LAM_THEM_TIEN_CONG_NGAY_LE { get; set; }
        public decimal TONG_THU_NHAP { get; set; }
        public decimal TAM_UNG { get; set; }
        public decimal VAY_TIN_DUNG { get; set; }
        public double GIO_DI_TRE { get; set; }
        public decimal PHAT_DI_TRE { get; set; }
        public decimal PHAT_QUEN_DONG_PHUC { get; set; }
        public decimal PHAT_QUEN_DEO_THE { get; set; }
        public decimal CONG_DOAN { get; set; }
        public decimal LUONG_LAO_CONG { get; set; }
        public decimal THUC_LINH { get; set; }
        public decimal PHU_CAP_THEM { get; set; }
    
        public virtual CCTC_NHAN_VIEN CCTC_NHAN_VIEN { get; set; }
    }
}
