//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTC_BANG_CHAM_CONG
    {
        public string THANG_CHAM_CONG { get; set; }
        public string USERNAME { get; set; }
        public int NGAY_CHUAN { get; set; }
        public double GIO_DI_MUON { get; set; }
        public double GIO_VE_SOM { get; set; }
        public double TANG_CA_NGAY_THUONG { get; set; }
        public double TANG_CA_NGAY_LE { get; set; }
        public double SO_LAN_QUEN_CHAM { get; set; }
        public double SO_NGAY_NGHI { get; set; }
        public double CONG_THUC_TE { get; set; }
        public decimal VAY_TIN_DUNG { get; set; }
        public decimal UNG_LUONG { get; set; }
        public string GHI_CHU { get; set; }
        public int SO_LAN_QUEN_DONG_PHUC { get; set; }
        public int SO_LAN_QUEN_DEO_THE { get; set; }
        public decimal PHU_CAP_THEM { get; set; }
    
        public virtual CCTC_NHAN_VIEN CCTC_NHAN_VIEN { get; set; }
    }
}
