//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ERP_DATABASEEntities : DbContext
    {
        public ERP_DATABASEEntities()
            : base("name=ERP_DATABASEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BH_BAO_GIA> BH_BAO_GIA { get; set; }
        public virtual DbSet<BH_CT_BAO_GIA> BH_CT_BAO_GIA { get; set; }
        public virtual DbSet<BH_DE_NGHI_GIU_HANG> BH_DE_NGHI_GIU_HANG { get; set; }
        public virtual DbSet<BH_DON_HANG_DU_KIEN> BH_DON_HANG_DU_KIEN { get; set; }
        public virtual DbSet<CATEGORy> CATEGORIES { get; set; }
        public virtual DbSet<CCTC_BANG_CHAM_CONG> CCTC_BANG_CHAM_CONG { get; set; }
        public virtual DbSet<CCTC_BANG_LUONG> CCTC_BANG_LUONG { get; set; }
        public virtual DbSet<CCTC_CONG_TY> CCTC_CONG_TY { get; set; }
        public virtual DbSet<CCTC_MO_HINH_CONG_TY> CCTC_MO_HINH_CONG_TY { get; set; }
        public virtual DbSet<CCTC_NHAN_VIEN> CCTC_NHAN_VIEN { get; set; }
        public virtual DbSet<CCTC_PHONG_BAN> CCTC_PHONG_BAN { get; set; }
        public virtual DbSet<CN_CHI_TIET_NGHIEP_VU> CN_CHI_TIET_NGHIEP_VU { get; set; }
        public virtual DbSet<CN_CHI_TIET_NHOM_NGHIEP_VU> CN_CHI_TIET_NHOM_NGHIEP_VU { get; set; }
        public virtual DbSet<CN_NGHIEP_VU> CN_NGHIEP_VU { get; set; }
        public virtual DbSet<CN_NGHIEP_VU_NHAN_VIEN> CN_NGHIEP_VU_NHAN_VIEN { get; set; }
        public virtual DbSet<CN_NHOM_NGHIEP_VU> CN_NHOM_NGHIEP_VU { get; set; }
        public virtual DbSet<CN_NHOM_NGUOI_DUNG_NGHIEP_VU> CN_NHOM_NGUOI_DUNG_NGHIEP_VU { get; set; }
        public virtual DbSet<DM_CHUNG_TU> DM_CHUNG_TU { get; set; }
        public virtual DbSet<DM_DINH_KHOAN_TU_DONG> DM_DINH_KHOAN_TU_DONG { get; set; }
        public virtual DbSet<DM_DOI_TUONG> DM_DOI_TUONG { get; set; }
        public virtual DbSet<DM_KHO> DM_KHO { get; set; }
        public virtual DbSet<DM_LOAI_CHUNG_TU> DM_LOAI_CHUNG_TU { get; set; }
        public virtual DbSet<DM_LOAI_DOI_TUONG> DM_LOAI_DOI_TUONG { get; set; }
        public virtual DbSet<DM_LOAI_TK_NGAN_HANG> DM_LOAI_TK_NGAN_HANG { get; set; }
        public virtual DbSet<DM_TAI_KHOAN_HACH_TOAN> DM_TAI_KHOAN_HACH_TOAN { get; set; }
        public virtual DbSet<DM_TK_NGAN_HANG_NOI_BO> DM_TK_NGAN_HANG_NOI_BO { get; set; }
        public virtual DbSet<DV> DVs { get; set; }
        public virtual DbSet<HH> HHs { get; set; }
        public virtual DbSet<HH_HANG_DUOC_QUAN_TAM> HH_HANG_DUOC_QUAN_TAM { get; set; }
        public virtual DbSet<HH_NHOM_VTHH> HH_NHOM_VTHH { get; set; }
        public virtual DbSet<HT_LICH_SU_DANG_NHAP> HT_LICH_SU_DANG_NHAP { get; set; }
        public virtual DbSet<HT_NGUOI_DUNG> HT_NGUOI_DUNG { get; set; }
        public virtual DbSet<KH> KHs { get; set; }
        public virtual DbSet<KH_CHUYEN_SALES> KH_CHUYEN_SALES { get; set; }
        public virtual DbSet<KH_DC_XUAT_HANG> KH_DC_XUAT_HANG { get; set; }
        public virtual DbSet<KH_LIEN_HE> KH_LIEN_HE { get; set; }
        public virtual DbSet<KH_LOAI> KH_LOAI { get; set; }
        public virtual DbSet<KH_PHAN_LOAI_KHACH> KH_PHAN_LOAI_KHACH { get; set; }
        public virtual DbSet<KH_SALES_PHU_TRACH> KH_SALES_PHU_TRACH { get; set; }
        public virtual DbSet<KH_TK_NGAN_HANG> KH_TK_NGAN_HANG { get; set; }
        public virtual DbSet<KHO_CHUYEN_KHO> KHO_CHUYEN_KHO { get; set; }
        public virtual DbSet<KHO_CT_CHUYEN_KHO> KHO_CT_CHUYEN_KHO { get; set; }
        public virtual DbSet<KHO_CT_DNXH> KHO_CT_DNXH { get; set; }
        public virtual DbSet<KHO_CT_GIU_HANG> KHO_CT_GIU_HANG { get; set; }
        public virtual DbSet<KHO_CT_NHAP_KHO> KHO_CT_NHAP_KHO { get; set; }
        public virtual DbSet<KHO_CT_XUAT_KHO> KHO_CT_XUAT_KHO { get; set; }
        public virtual DbSet<KHO_DNXH> KHO_DNXH { get; set; }
        public virtual DbSet<KHO_GIU_HANG> KHO_GIU_HANG { get; set; }
        public virtual DbSet<KHO_NHAP_KHO> KHO_NHAP_KHO { get; set; }
        public virtual DbSet<KHO_XUAT_KHO> KHO_XUAT_KHO { get; set; }
        public virtual DbSet<MAU_SO_HOA_DON> MAU_SO_HOA_DON { get; set; }
        public virtual DbSet<MENU> MENUs { get; set; }
        public virtual DbSet<MENU_USER> MENU_USER { get; set; }
        public virtual DbSet<MH_CT_MDV> MH_CT_MDV { get; set; }
        public virtual DbSet<MH_MDV> MH_MDV { get; set; }
        public virtual DbSet<NCC> NCCs { get; set; }
        public virtual DbSet<NCC_LIEN_HE> NCC_LIEN_HE { get; set; }
        public virtual DbSet<NCC_LOAI> NCC_LOAI { get; set; }
        public virtual DbSet<NCC_LOAI_HANG_CUNG_CAP> NCC_LOAI_HANG_CUNG_CAP { get; set; }
        public virtual DbSet<NCC_PUR_PHU_TRACH> NCC_PUR_PHU_TRACH { get; set; }
        public virtual DbSet<NCC_TK_NGAN_HANG> NCC_TK_NGAN_HANG { get; set; }
        public virtual DbSet<NH_CHUYEN_TIEN_NOI_BO> NH_CHUYEN_TIEN_NOI_BO { get; set; }
        public virtual DbSet<NH_CT_NTTK> NH_CT_NTTK { get; set; }
        public virtual DbSet<NH_CT_UNC> NH_CT_UNC { get; set; }
        public virtual DbSet<NH_NTTK> NH_NTTK { get; set; }
        public virtual DbSet<NH_UNC> NH_UNC { get; set; }
        public virtual DbSet<NV_GIAO_VIEC> NV_GIAO_VIEC { get; set; }
        public virtual DbSet<NV_LICH_LAM_VIEC> NV_LICH_LAM_VIEC { get; set; }
        public virtual DbSet<NV_TINH_LUONG> NV_TINH_LUONG { get; set; }
        public virtual DbSet<POST_CATEGORIES> POST_CATEGORIES { get; set; }
        public virtual DbSet<POST> POSTS { get; set; }
        public virtual DbSet<QUY_CT_PHIEU_CHI> QUY_CT_PHIEU_CHI { get; set; }
        public virtual DbSet<QUY_CT_PHIEU_THU> QUY_CT_PHIEU_THU { get; set; }
        public virtual DbSet<QUY_PHIEU_CHI> QUY_PHIEU_CHI { get; set; }
        public virtual DbSet<QUY_PHIEU_THU> QUY_PHIEU_THU { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TONKHO_GIU_HL> TONKHO_GIU_HL { get; set; }
        public virtual DbSet<TONKHO_GIU_TADN> TONKHO_GIU_TADN { get; set; }
        public virtual DbSet<TONKHO_GIU_TAHCM> TONKHO_GIU_TAHCM { get; set; }
        public virtual DbSet<TONKHO_GIU_TAHP> TONKHO_GIU_TAHP { get; set; }
        public virtual DbSet<TONKHO_HANG> TONKHO_HANG { get; set; }
        public virtual DbSet<TONKHO_HANG_DANG_VE> TONKHO_HANG_DANG_VE { get; set; }
        public virtual DbSet<TONKHO_HOPLONG> TONKHO_HOPLONG { get; set; }
        public virtual DbSet<TONKHO_KYGUI_HL> TONKHO_KYGUI_HL { get; set; }
        public virtual DbSet<TONKHO_KYGUI_TADN> TONKHO_KYGUI_TADN { get; set; }
        public virtual DbSet<TONKHO_KYGUI_TAHCM> TONKHO_KYGUI_TAHCM { get; set; }
        public virtual DbSet<TONKHO_KYGUI_TAHP> TONKHO_KYGUI_TAHP { get; set; }
        public virtual DbSet<TONKHO_TADN> TONKHO_TADN { get; set; }
        public virtual DbSet<TONKHO_TAHCM> TONKHO_TAHCM { get; set; }
        public virtual DbSet<TONKHO_TAHP> TONKHO_TAHP { get; set; }
        public virtual DbSet<XL_DANG_KY_PHE_DUYET> XL_DANG_KY_PHE_DUYET { get; set; }
        public virtual DbSet<XL_THAM_CHIEU_CHUNG_TU> XL_THAM_CHIEU_CHUNG_TU { get; set; }
    
        public virtual int PROD_HANGHOA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROD_HANGHOA");
        }
    
        public virtual ObjectResult<XL_TimKiemHangHoa_Result> XL_TimKiemHangHoa(string tukhoa)
        {
            var tukhoaParameter = tukhoa != null ?
                new ObjectParameter("tukhoa", tukhoa) :
                new ObjectParameter("tukhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<XL_TimKiemHangHoa_Result>("XL_TimKiemHangHoa", tukhoaParameter);
        }
    
        public virtual ObjectResult<BaiVietTheoDanhMuc_Result> BaiVietTheoDanhMuc(string tukhoa)
        {
            var tukhoaParameter = tukhoa != null ?
                new ObjectParameter("tukhoa", tukhoa) :
                new ObjectParameter("tukhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BaiVietTheoDanhMuc_Result>("BaiVietTheoDanhMuc", tukhoaParameter);
        }
    
        public virtual ObjectResult<string> XL_LayMaKhachMoiNhat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("XL_LayMaKhachMoiNhat");
        }
    
        public virtual ObjectResult<string> XL_LayMaGiuHangMoiNhat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("XL_LayMaGiuHangMoiNhat");
        }
    
        public virtual ObjectResult<LocKHTheoSale_Result> LocKHTheoSale(string sale)
        {
            var saleParameter = sale != null ?
                new ObjectParameter("sale", sale) :
                new ObjectParameter("sale", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LocKHTheoSale_Result>("LocKHTheoSale", saleParameter);
        }
    
        public virtual ObjectResult<GetAll_KhachHang_Result> GetAll_KhachHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAll_KhachHang_Result>("GetAll_KhachHang");
        }
    
        public virtual ObjectResult<TimKiemKhachHang_Result> TimKiemKhachHang(string sdt)
        {
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimKiemKhachHang_Result>("TimKiemKhachHang", sdtParameter);
        }
    
        public virtual ObjectResult<HopLong_LocKHTheoSale_Result> HopLong_LocKHTheoSale(string sale, string sdt)
        {
            var saleParameter = sale != null ?
                new ObjectParameter("sale", sale) :
                new ObjectParameter("sale", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HopLong_LocKHTheoSale_Result>("HopLong_LocKHTheoSale", saleParameter, sdtParameter);
        }
    
        public virtual ObjectResult<HopLong_GetAllSale_Result> HopLong_GetAllSale()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HopLong_GetAllSale_Result>("HopLong_GetAllSale");
        }
    
        public virtual ObjectResult<HopLong_DS_TONKHO_Result> HopLong_DS_TONKHO(string mA_CHUAN)
        {
            var mA_CHUANParameter = mA_CHUAN != null ?
                new ObjectParameter("MA_CHUAN", mA_CHUAN) :
                new ObjectParameter("MA_CHUAN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HopLong_DS_TONKHO_Result>("HopLong_DS_TONKHO", mA_CHUANParameter);
        }
    
        public virtual ObjectResult<HopLong_PhanTrang_TonKho_Result> HopLong_PhanTrang_TonKho(Nullable<int> sotrang)
        {
            var sotrangParameter = sotrang.HasValue ?
                new ObjectParameter("sotrang", sotrang) :
                new ObjectParameter("sotrang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HopLong_PhanTrang_TonKho_Result>("HopLong_PhanTrang_TonKho", sotrangParameter);
        }
    
        public virtual ObjectResult<GetAll_LienHeTheoKhach_Result> GetAll_LienHeTheoKhach(string makhachhang)
        {
            var makhachhangParameter = makhachhang != null ?
                new ObjectParameter("makhachhang", makhachhang) :
                new ObjectParameter("makhachhang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAll_LienHeTheoKhach_Result>("GetAll_LienHeTheoKhach", makhachhangParameter);
        }
    
        public virtual ObjectResult<GetAll_KhachCuaSale_Result> GetAll_KhachCuaSale(string macongty, string sale)
        {
            var macongtyParameter = macongty != null ?
                new ObjectParameter("macongty", macongty) :
                new ObjectParameter("macongty", typeof(string));
    
            var saleParameter = sale != null ?
                new ObjectParameter("sale", sale) :
                new ObjectParameter("sale", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAll_KhachCuaSale_Result>("GetAll_KhachCuaSale", macongtyParameter, saleParameter);
        }
    
        public virtual ObjectResult<GetAllChungTu_Result> GetAllChungTu(string macongty)
        {
            var macongtyParameter = macongty != null ?
                new ObjectParameter("macongty", macongty) :
                new ObjectParameter("macongty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllChungTu_Result>("GetAllChungTu", macongtyParameter);
        }
    
        public virtual ObjectResult<GetAllChungTu_WithDate_Result> GetAllChungTu_WithDate(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, string macongty)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var macongtyParameter = macongty != null ?
                new ObjectParameter("macongty", macongty) :
                new ObjectParameter("macongty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllChungTu_WithDate_Result>("GetAllChungTu_WithDate", fromDateParameter, toDateParameter, macongtyParameter);
        }
    
        public virtual ObjectResult<GetAllHangHoaVaTon_Result> GetAllHangHoaVaTon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllHangHoaVaTon_Result>("GetAllHangHoaVaTon");
        }
    
        public virtual ObjectResult<GetChungTuFromDoiTuong_Result> GetChungTuFromDoiTuong(string maDoiTuong, string macongty)
        {
            var maDoiTuongParameter = maDoiTuong != null ?
                new ObjectParameter("MaDoiTuong", maDoiTuong) :
                new ObjectParameter("MaDoiTuong", typeof(string));
    
            var macongtyParameter = macongty != null ?
                new ObjectParameter("macongty", macongty) :
                new ObjectParameter("macongty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetChungTuFromDoiTuong_Result>("GetChungTuFromDoiTuong", maDoiTuongParameter, macongtyParameter);
        }
    
        public virtual ObjectResult<GetChungTuFromDoiTuong_WithDate_Result> GetChungTuFromDoiTuong_WithDate(string maDoiTuong, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, string macongty)
        {
            var maDoiTuongParameter = maDoiTuong != null ?
                new ObjectParameter("MaDoiTuong", maDoiTuong) :
                new ObjectParameter("MaDoiTuong", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var macongtyParameter = macongty != null ?
                new ObjectParameter("macongty", macongty) :
                new ObjectParameter("macongty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetChungTuFromDoiTuong_WithDate_Result>("GetChungTuFromDoiTuong_WithDate", maDoiTuongParameter, fromDateParameter, toDateParameter, macongtyParameter);
        }
    
        public virtual ObjectResult<Search_SearchByType_Result> Search_SearchByType(string loaiChungTu, string macongty)
        {
            var loaiChungTuParameter = loaiChungTu != null ?
                new ObjectParameter("LoaiChungTu", loaiChungTu) :
                new ObjectParameter("LoaiChungTu", typeof(string));
    
            var macongtyParameter = macongty != null ?
                new ObjectParameter("macongty", macongty) :
                new ObjectParameter("macongty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_SearchByType_Result>("Search_SearchByType", loaiChungTuParameter, macongtyParameter);
        }
    
        public virtual ObjectResult<Search_SearchByTypeWithDate_Result> Search_SearchByTypeWithDate(string loaiChungTu, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, string macongty)
        {
            var loaiChungTuParameter = loaiChungTu != null ?
                new ObjectParameter("LoaiChungTu", loaiChungTu) :
                new ObjectParameter("LoaiChungTu", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var macongtyParameter = macongty != null ?
                new ObjectParameter("macongty", macongty) :
                new ObjectParameter("macongty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_SearchByTypeWithDate_Result>("Search_SearchByTypeWithDate", loaiChungTuParameter, fromDateParameter, toDateParameter, macongtyParameter);
        }
    
        public virtual ObjectResult<GetAllDoiTuong_Result> GetAllDoiTuong(string macongty)
        {
            var macongtyParameter = macongty != null ?
                new ObjectParameter("macongty", macongty) :
                new ObjectParameter("macongty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllDoiTuong_Result>("GetAllDoiTuong", macongtyParameter);
        }
    }
}
