//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CHUNG_TU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_CHUNG_TU()
        {
            this.XL_THAM_CHIEU_CHUNG_TU = new HashSet<XL_THAM_CHIEU_CHUNG_TU>();
            this.XL_THAM_CHIEU_CHUNG_TU1 = new HashSet<XL_THAM_CHIEU_CHUNG_TU>();
        }
    
        public string MA_CHUNG_TU { get; set; }
        public string TEN_CHUNG_TU { get; set; }
        public string MA_LOAI_CHUNG_TU { get; set; }
        public string MA_CONG_TY { get; set; }
        public Nullable<System.DateTime> NGAY_CHUNG_TU { get; set; }
        public string DOI_TUONG { get; set; }
    
        public virtual CCTC_CONG_TY CCTC_CONG_TY { get; set; }
        public virtual DM_DOI_TUONG DM_DOI_TUONG { get; set; }
        public virtual DM_LOAI_CHUNG_TU DM_LOAI_CHUNG_TU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XL_THAM_CHIEU_CHUNG_TU> XL_THAM_CHIEU_CHUNG_TU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XL_THAM_CHIEU_CHUNG_TU> XL_THAM_CHIEU_CHUNG_TU1 { get; set; }
    }
}
