//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    
    public partial class GetAll_DS_PhieuXuatKho_Result1
    {
        public string SO_CHUNG_TU { get; set; }
        public string NGAY_HACH_TOAN { get; set; }
        public string NGAY_CHUNG_TU { get; set; }
        public string TEN_CONG_TY { get; set; }
        public string LOAI_XUAT_KHO { get; set; }
        public string KHACH_HANG { get; set; }
        public string LY_DO_XUAT { get; set; }
        public string NGUOI_LAP_PHIEU { get; set; }
        public string NGUOI_NHAN { get; set; }
        public string NHAN_VIEN_BAN_HANG { get; set; }
        public decimal TONG_TIEN { get; set; }
        public string TRUC_THUOC { get; set; }
    }
}
