//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH_DC_XUAT_HANG
    {
        public int ID { get; set; }
        public string MA_KHACH_HANG { get; set; }
        public string DIA_CHI_XUAT_HANG { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual KH KH { get; set; }
    }
}
