//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH_PHAN_LOAI_KHACH
    {
        public int ID { get; set; }
        public string MA_KHACH_HANG { get; set; }
        public string MA_LOAI_KHACH { get; set; }
        public string NHOM_NGANH { get; set; }
    
        public virtual KH KH { get; set; }
        public virtual KH_LOAI KH_LOAI { get; set; }
    }
}
