//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO_CT_GIU_HANG
    {
        public int ID { get; set; }
        public string MA_GIU_KHO { get; set; }
        public string MA_HANG { get; set; }
        public int SL_GIU { get; set; }
        public Nullable<System.DateTime> NGAY_XUAT { get; set; }
        public bool DA_XUAT { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual HH HH { get; set; }
        public virtual KHO_GIU_HANG KHO_GIU_HANG { get; set; }
    }
}
