//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO_GIU_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHO_GIU_HANG()
        {
            this.KHO_CT_GIU_HANG = new HashSet<KHO_CT_GIU_HANG>();
        }
    
        public string MA_GIU_KHO { get; set; }
        public string SALES_GIU { get; set; }
        public string MA_KHACH_HANG { get; set; }
        public System.DateTime NGAY_GIU { get; set; }
        public bool HUY_DON_GIU { get; set; }
        public bool GIU_PO { get; set; }
        public bool DON_DANG_XUAT { get; set; }
        public bool DON_DA_HOAN_THANH { get; set; }
        public string TRUC_THUOC { get; set; }
    
        public virtual CCTC_CONG_TY CCTC_CONG_TY { get; set; }
        public virtual CCTC_NHAN_VIEN CCTC_NHAN_VIEN { get; set; }
        public virtual KH KH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHO_CT_GIU_HANG> KHO_CT_GIU_HANG { get; set; }
    }
}
