//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_USER
    {
        public string MA_PHONG_BAN { get; set; }
        public string USERNAME { get; set; }
        public string MA_MENU { get; set; }
        public bool TRANG_THAI { get; set; }
    
        public virtual CCTC_NHAN_VIEN CCTC_NHAN_VIEN { get; set; }
        public virtual CCTC_PHONG_BAN CCTC_PHONG_BAN { get; set; }
        public virtual MENU MENU { get; set; }
    }
}
