//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCC_LOAI_HANG_CUNG_CAP
    {
        public int ID { get; set; }
        public string MA_NHA_CUNG_CAP { get; set; }
        public string MA_NHOM_HANG { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual HH_NHOM_VTHH HH_NHOM_VTHH { get; set; }
        public virtual NCC NCC { get; set; }
    }
}
