//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NH_UNC
    {
        public string SO_CHUNG_TU { get; set; }
        public System.DateTime NGAY_HACH_TOAN { get; set; }
        public System.DateTime NGAY_CHUNG_TU { get; set; }
        public string TAI_KHOAN_CHI { get; set; }
        public string MA_DOI_TUONG { get; set; }
        public string NOI_DUNG_THANH_TOAN { get; set; }
        public string DIEN_GIAI_NOI_DUNG_THANH_TOAN { get; set; }
        public string TAI_KHOAN_NHAN { get; set; }
        public string NHAN_VIEN_CHUYEN_KHOAN { get; set; }
        public string NGUOI_LAP_BIEU { get; set; }
        public decimal TONG_TIEN { get; set; }
        public string TRUC_THUOC { get; set; }
    
        public virtual CCTC_CONG_TY CCTC_CONG_TY { get; set; }
        public virtual DM_DOI_TUONG DM_DOI_TUONG { get; set; }
        public virtual DM_TK_NGAN_HANG_NOI_BO DM_TK_NGAN_HANG_NOI_BO { get; set; }
        public virtual HT_NGUOI_DUNG HT_NGUOI_DUNG { get; set; }
        public virtual HT_NGUOI_DUNG HT_NGUOI_DUNG1 { get; set; }
    }
}
