//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_TINH_LUONG
    {
        public string USERNAME { get; set; }
        public decimal LUONG_CO_BAN { get; set; }
        public decimal LUONG_BAO_HIEM { get; set; }
        public decimal PHU_CAP_AN_TRUA { get; set; }
        public decimal PHU_CAP_DI_LAI_DIEN_THOAI { get; set; }
        public decimal PHU_CAP_TRACH_NHIEM { get; set; }
        public decimal LUONG_LAO_CONG { get; set; }
    
        public virtual CCTC_NHAN_VIEN CCTC_NHAN_VIEN { get; set; }
    }
}
