//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONKHO_HANG
    {
        public string MA_HANG { get; set; }
        public string MA_NHOM_HANG { get; set; }
        public int SL_HANG { get; set; }
        public string THOI_GIAN_CAP_HANG { get; set; }
    
        public virtual HH HH { get; set; }
        public virtual HH_NHOM_VTHH HH_NHOM_VTHH { get; set; }
    }
}
