//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class XL_THAM_CHIEU_CHUNG_TU
    {
        public int ID { get; set; }
        public string SO_CHUNG_TU_GOC { get; set; }
        public string SO_CHUNG_TU_THAM_CHIEU { get; set; }
    
        public virtual DM_CHUNG_TU DM_CHUNG_TU { get; set; }
        public virtual DM_CHUNG_TU DM_CHUNG_TU1 { get; set; }
    }
}
